# -*- coding: utf-8 -*-
"""Advanced Excel Assignment .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/149Yew3JNnMenTclOoJSOpBNVvUzO2y31

# Advanced Excel Assignment

1. Explain the difference between Absolute, Relative, and Mixed Cell
Referencing in Excel with examples.
 - Relative Cell Reference

A relative reference changes automatically when you copy the formula to another cell.

Example

    If cell C1 has:

    =A1+B1

When copied to C2, it becomes:

=A2+B2

Because Excel adjusts the row numbers automatically.

Use Case

Used when performing the same calculation for multiple rows or columns.

 > Absolute Cell Reference

An absolute reference keeps the cell fixed using $.

Example

If cell B1 contains tax rate 10% and formula in C2 is:

    =A2*$B$1

When copied downward, $B$1 remains fixed.

Why?

Because both column B and row 1 are locked.

Use Case

Used for fixed values like:

Tax rates
Commission %
Constants
Lookup tables

> Mixed Cell Reference

A mixed reference locks either:

only the row, or
only the column.
Types
Reference	Fixed Part
$A1	Column fixed
A$1	Row fixed
Example

    1: $A1

Column A stays fixed
Row changes

Copied downward:

    $A1 → $A2 → $A3

Use Case

Useful in:

Multiplication tables

Matrix calculations

Structured data formulas

Quick Memory Trick

Symbol	Meaning

A1	Nothing locked

$A$1	Everything locked

$A1	Column locked

A$1	Row locked

2. What is a Macro in Excel? How does it help in automation?
 - A Macro in Microsoft Excel is a recorded set of actions or instructions that automates repetitive tasks.

Macros are usually written in VBA (Visual Basic for Applications), which is Excel’s programming language.

Instead of doing the same steps again and again manually, you can create a macro and run it with one click.

How Macros Help in Automation

Macros automate repetitive work, which:

Saves time
Reduces manual effort
Minimizes errors
Increases productivity
Example of a Macro

Suppose every day you:

Open a sales file

Make headings bold

Apply filters

Adjust column widths

Create a report

Doing this manually daily takes time.

With a macro:

You record these steps once

Excel repeats them automatically whenever needed

Common Tasks Automated Using Macros

Formatting reports

Data cleaning

Creating charts

Generating invoices

Applying formulas

Sorting and filtering data

Sending automated emails

Importing/exporting data

Types of Macros

Type	Description

Recorded Macro	Created by recording user actions
VBA Macro	Written manually using VBA code

Simple VBA Macro Example

Sub Hello()

    MsgBox "Welcome to Excel Macro!"

End Sub

This macro displays a message box.

Steps to Create a Macro

Open Excel

Go to Developer Tab

Click Record Macro

Perform actions

Click Stop Recording

Now the macro can repeat those actions automatically.

>Advantages of Macros

Faster work completion

Useful for large datasets

Reduces repetitive tasks

Standardizes processes

Helpful in reporting and data analysis

>Disadvantages of Macros

Requires basic VBA knowledge for advanced use

Macro-enabled files may have security restrictions

Errors in VBA code can affect data

3. What are Text Functions in Excel? Mention any five with examples.
 - Text Functions in Excel are used to manipulate, combine, extract, or modify text data in cells. They help in cleaning and organizing textual information easily.

Here are five important text functions with examples:

>LEN() Function

Purpose: Counts the number of characters in a text.

Example:

=LEN("Excel")

Result: 5

>UPPER() Function

Purpose: Converts text into uppercase letters.

Example:

=UPPER("hello")

Result: HELLO

>LOWER() Function

Purpose: Converts text into lowercase letters.

Example:

=LOWER("WORLD")

Result: world

>CONCAT() Function

Purpose: Joins two or more text strings together.

Example:

=CONCAT("Data"," ","Analyst")

Result: Data Analyst

>LEFT() Function

Purpose: Extracts characters from the left side of text.

Example:

=LEFT("Computer",4)

Result: Comp

4. What is the use of Scenario Manager in decision making?
 - Scenario Manager in Excel is a What-If Analysis tool used to compare different sets of values and analyze possible outcomes. It helps in decision making by showing how changing input values affects the final result.

>Uses of Scenario Manager

Helps compare different business situations.

Predicts possible outcomes like profit, loss, budget, or sales.

Assists managers in planning and forecasting.

Useful for financial analysis and risk analysis.

Example

Suppose a company wants to check profit under three situations:

    Best Case → High sales
    Average Case → Normal sales
    Worst Case → Low sales

Using Scenario Manager, all these scenarios can be stored and compared without changing the original worksheet repeatedly.

>Steps to Use Scenario Manager

    Go to Data tab
    Click What-If Analysis
    Select Scenario Manager
    Add different scenarios with different values
    Compare the results

So, Scenario Manager helps users make better decisions by analyzing multiple possibilities before taking action.

5. Define the purpose of VLOOKUP and HLOOKUP. How are they different
from XLOOKUP? Which among XLOOKUP and INDEX-MATCH is best while usage?
 - VLOOKUP

VLOOKUP stands for Vertical Lookup.

It is used to search for a value in the first column of a table and return a value from another column in the same row.

Example

    =VLOOKUP(101, A2:D10, 3, FALSE)

This formula searches for 101 in column A and returns the value from the 3rd column.

>HLOOKUP

HLOOKUP stands for Horizontal Lookup.

It is used to search for a value in the first row of a table and return a value from another row.

Example

    =HLOOKUP("Jan", A1:F5, 3, FALSE)

This formula searches for "Jan" in the first row and returns the value from the 3rd row.

>Difference Between VLOOKUP/HLOOKUP and XLOOKUP

VLOOKUP and HLOOKUP

    Can search only in one direction.
    Need column or row number manually.
    Less flexible.
    Exact match is not default.

>XLOOKUP

    Can search in any direction.
    No need to count column numbers.
    Exact match by default.
    More flexible and easier to use.
    Has built-in error handling.

Example of XLOOKUP

    =XLOOKUP(101, A2:A10, C2:C10)

This formula searches for 101 and returns the matching value from column C.

>XLOOKUP vs INDEX-MATCH

>XLOOKUP

    Easier to write and understand.
    Modern and powerful function.
    Better for most users.

>INDEX-MATCH

    Works in older Excel versions.
    More flexible for advanced users.
    Useful for complex lookups.

Example of INDEX-MATCH

    =INDEX(C2:C10, MATCH(101, A2:A10, 0))

Conclusion

XLOOKUP is generally the best because it is simple, flexible, and powerful.
INDEX-MATCH is preferred when using older Excel versions or advanced lookup operations.
"""